name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'   # speed & fewer network calls

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # This step is nice-to-have. Network hiccups shouldn't fail CI.
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
        continue-on-error: true

      # Retry build a few times in case of transient network outages
      - name: Build & Test (with retry)
        run: |
          set -e
          for i in 1 2 3; do
            echo "Attempt $i"
            ./gradlew --no-daemon clean build test && exit 0
            echo "Gradle failed, retrying in 15s..."
            sleep 15
          done
          echo "Gradle failed after 3 attempts"
          exit 1

      - name: Upload Test Reports (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            build/reports/tests/
            build/test-results/